name: Wii

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sed -i '/^\[dkp-libs\]$/,$d' /opt/devkitpro/pacman/etc/pacman.conf
        dkp-pacman-key --recv-keys C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE --keyserver keyserver.ubuntu.com
        dkp-pacman-key --finger C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        dkp-pacman-key --lsign-key C8A2759C315CFBC3429CC2E422B803BA8AA3D7CE
        echo "[extremscorner-devkitpro]" >> /opt/devkitpro/pacman/etc/pacman.conf
        echo "Server = https://packages.extremscorner.org/devkitpro/linux/$arch" >> /opt/devkitpro/pacman/etc/pacman.conf
        dkp-pacman -Sy --noconfirm libogc2-ntfs

    - name: Build
      run: |
        make -j2
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: .
