name: Wii

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pacman -S libogc2-libntfs ppc-mxml

    - name: Build
      run: |
        make -j2
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: .
